### ISSUE TITLE
Update FastSRM install_requires for pip deprecation

### ISSUE THREAD

**Issue by emdupre** [hugorichard/FastSRM#6]
When adding fastSRM as an fmralign dependency, we [see a build failure](https://github.com/Parietal-INRIA/fmralign/actions/runs/6090109884/job/16524314628). Local installation confirms this is a deprecation from pip:

> DEPRECATION: fastsrm 0.0.4 has a non-standard dependency specifier scipy>=0.18.0numpy>=1.12scikit-learn>=0.23joblib>=1.1.0matplotlib>=2.0.0pytest>=6.2.5. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of fastsrm or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

We can correct this by adding delimiters in fastSRM's [install_requires](https://github.com/hugorichard/FastSRM/blob/af8c24fc044f040d05376dc3892879e0493a8bf8/setup.py#L14-L21).

I'll open a PR for this, but please let me know how you'd like to handle longer term maintenance, @hugorichard  ! i.e., should we vendor the relevant code within fmralign ? Any thoughts are appreciated !

**Comment by hugorichard** [comment]
Thanks Elisabeth,
This seems like a simple issue to deal with. I'll take some time today to
try to take care of it. If I fail. We will move the code to fMRI align.

Le ven. 8 sept. 2023 à 00:51, Elizabeth DuPre ***@***.***> a
écrit :

**Comment by hugorichard** [comment]
I believe it is solved now

**Comment by bthirion** [comment]
Thx !

**Comment by emdupre** [comment]
Thank you, @hugorichard !

**Comment by emdupre** [comment]
Closing as the fmralign build is now passing 🚀  Thanks again for updating this !!
